apiVersion: v2
name: s2i
description: Creates an image stream from a Docker file in github and run that app with route exposed. Also creates a shortcut link in console 9box.
appVersion: "1.16.0"
type: application
version: 0.0.2