{{- if .Values.operators.servicemesh }}
apiVersion: operators.coreos.com/v1
kind: Operator
metadata:
  name: servicemeshoperator.openshift-operators
--- 
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}

